//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crime()
        {
            this.FatoEstabelecimento = new HashSet<FatoEstabelecimento>();
            this.FatoSistemaPenitenciario = new HashSet<FatoSistemaPenitenciario>();
        }
    
        public int SkCrime { get; set; }
        public int NkUnidade { get; set; }
        public string RecebeAtestadoPenaACumprir { get; set; }
        public Nullable<System.DateTime> DataInsercao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoEstabelecimento> FatoEstabelecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoSistemaPenitenciario> FatoSistemaPenitenciario { get; set; }
    }
}
