//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DW_SISDPEntities : DbContext
    {
        public DW_SISDPEntities()
            : base("name=DW_SISDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Erro> Erro { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Crime> Crime { get; set; }
        public virtual DbSet<Educacao> Educacao { get; set; }
        public virtual DbSet<PopulacaoPrisional> PopulacaoPrisional { get; set; }
        public virtual DbSet<Saude> Saude { get; set; }
        public virtual DbSet<ServicosTerceirizados> ServicosTerceirizados { get; set; }
        public virtual DbSet<Tempo> Tempo { get; set; }
        public virtual DbSet<Trabalho> Trabalho { get; set; }
        public virtual DbSet<UF> UF { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
        public virtual DbSet<FatoEstabelecimento> FatoEstabelecimento { get; set; }
        public virtual DbSet<FatoSistemaPenitenciario> FatoSistemaPenitenciario { get; set; }
        public virtual DbSet<vwUnidade> vwUnidade { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<Top10ObitosPorUnidade_Result> Top10ObitosPorUnidade()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Top10ObitosPorUnidade_Result>("Top10ObitosPorUnidade");
        }
    
        public virtual ObjectResult<UnidadesPorUF_Result> UnidadesPorUF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnidadesPorUF_Result>("UnidadesPorUF");
        }
    
        public virtual ObjectResult<AtividadeEducacional_Result> AtividadeEducacional(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AtividadeEducacional_Result>("AtividadeEducacional", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Biblioteca_Result> Biblioteca(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Biblioteca_Result>("Biblioteca", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Escolaridade_Result> Escolaridade(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Escolaridade_Result>("Escolaridade", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<InfGrauInstrucao_Result> InfGrauInstrucao(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InfGrauInstrucao_Result>("InfGrauInstrucao", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Oficina_Result> Oficina(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Oficina_Result>("Oficina", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<SalaAula_Result> SalaAula(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaAula_Result>("SalaAula", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<SalaInformatica_Result> SalaInformatica(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaInformatica_Result>("SalaInformatica", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<SalaProfessores_Result> SalaProfessores(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaProfessores_Result>("SalaProfessores", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ConsultasEmGeral_Result> ConsultasEmGeral(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultasEmGeral_Result>("ConsultasEmGeral", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ConsultorioMedico_Result> ConsultorioMedico(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultorioMedico_Result>("ConsultorioMedico", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ConsultorioOdonto_Result> ConsultorioOdonto(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultorioOdonto_Result>("ConsultorioOdonto", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Doencas_Result> Doencas(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Doencas_Result>("Doencas", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Farmacia_Result> Farmacia(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Farmacia_Result>("Farmacia", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Mortes_Result> Mortes(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Mortes_Result>("Mortes", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<RelatorioSinteticoSaude_Result> RelatorioSinteticoSaude(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RelatorioSinteticoSaude_Result>("RelatorioSinteticoSaude", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ServidoresSaude_Result> ServidoresSaude(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServidoresSaude_Result>("ServidoresSaude", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ServidoresEducacao_Result> ServidoresEducacao(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServidoresEducacao_Result>("ServidoresEducacao", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ServidoresAdministrativo_Result> ServidoresAdministrativo(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServidoresAdministrativo_Result>("ServidoresAdministrativo", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ServidoresSeguranca_Result> ServidoresSeguranca(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ServidoresSeguranca_Result>("ServidoresSeguranca", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Homicidios_Result> Homicidios(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Homicidios_Result>("Homicidios", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Lesao_Result> Lesao(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lesao_Result>("Lesao", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<ArmaFogo_Result> ArmaFogo(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ArmaFogo_Result>("ArmaFogo", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<AtestadoPena_Result> AtestadoPena(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AtestadoPena_Result>("AtestadoPena", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Corrupcao_Result> Corrupcao(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Corrupcao_Result>("Corrupcao", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<CrimeSexual_Result> CrimeSexual(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CrimeSexual_Result>("CrimeSexual", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<FurtoRoubo_Result> FurtoRoubo(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FurtoRoubo_Result>("FurtoRoubo", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<TipificacaoCriminal_Result> TipificacaoCriminal(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipificacaoCriminal_Result>("TipificacaoCriminal", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<TraficoDrogas_Result> TraficoDrogas(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraficoDrogas_Result>("TraficoDrogas", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<TempoPena_Result> TempoPena(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TempoPena_Result>("TempoPena", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<TempoPenaRemanescente_Result> TempoPenaRemanescente(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TempoPenaRemanescente_Result>("TempoPenaRemanescente", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<AuxilioReclusao_Result> AuxilioReclusao(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuxilioReclusao_Result>("AuxilioReclusao", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Deficiente_Result> Deficiente(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Deficiente_Result>("Deficiente", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<EstadoCivil_Result> EstadoCivil(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstadoCivil_Result>("EstadoCivil", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Filhos_Result> Filhos(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Filhos_Result>("Filhos", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<InclusoesRemocoes_Result> InclusoesRemocoes(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InclusoesRemocoes_Result>("InclusoesRemocoes", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Naturalidade_Result> Naturalidade(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Naturalidade_Result>("Naturalidade", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<PresosPorIdade_Result> PresosPorIdade(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PresosPorIdade_Result>("PresosPorIdade", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<PresosPorRaca_Result> PresosPorRaca(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PresosPorRaca_Result>("PresosPorRaca", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<PresosPorRegime_Result> PresosPorRegime(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PresosPorRegime_Result>("PresosPorRegime", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    
        public virtual ObjectResult<Remuneracao_Result> Remuneracao(Nullable<int> skUF, Nullable<int> nkCidade, Nullable<int> nkUnidade)
        {
            var skUFParameter = skUF.HasValue ?
                new ObjectParameter("SkUF", skUF) :
                new ObjectParameter("SkUF", typeof(int));
    
            var nkCidadeParameter = nkCidade.HasValue ?
                new ObjectParameter("NkCidade", nkCidade) :
                new ObjectParameter("NkCidade", typeof(int));
    
            var nkUnidadeParameter = nkUnidade.HasValue ?
                new ObjectParameter("NkUnidade", nkUnidade) :
                new ObjectParameter("NkUnidade", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Remuneracao_Result>("Remuneracao", skUFParameter, nkCidadeParameter, nkUnidadeParameter);
        }
    }
}
