//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Erro
    {
        public int Id { get; set; }
        public Nullable<long> ErrorCode { get; set; }
        public string ErrorColumn { get; set; }
        public Nullable<System.DateTime> DataErro { get; set; }
        public Nullable<int> NK_UNIDADE { get; set; }
    }
}
