//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FatoSistemaPenitenciario
    {
        public int SkSistemaPenitenciario { get; set; }
        public Nullable<int> SkUnidade { get; set; }
        public Nullable<int> SkSaude { get; set; }
        public Nullable<int> SkEducacao { get; set; }
        public Nullable<int> SkTempo { get; set; }
        public Nullable<int> SkCrime { get; set; }
        public Nullable<int> SkTrabalho { get; set; }
        public int SkPopulacaoPrisional { get; set; }
        public Nullable<int> SkServicosTerceirizados { get; set; }
        public Nullable<short> QtdAdministrativoEfetivoM { get; set; }
        public Nullable<short> QtdAdministrativoEfetivoF { get; set; }
        public Nullable<short> QtdAdministrativoComisM { get; set; }
        public Nullable<short> QtdAdministrativoComisF { get; set; }
        public Nullable<short> QtdAdministrativoTercM { get; set; }
        public Nullable<short> QtdAdministrativoTercF { get; set; }
        public Nullable<short> QtdAdministrativoTempM { get; set; }
        public Nullable<short> QtdAdministrativoTempF { get; set; }
        public Nullable<short> QtdEnfermeiroEfetivoM { get; set; }
        public Nullable<short> QtdEnfermeiroEfetivoF { get; set; }
        public Nullable<short> QtdEnfermeiroComisM { get; set; }
        public Nullable<short> QtdEnfermeiroComisF { get; set; }
        public Nullable<short> QtdEnfermeiroTercM { get; set; }
        public Nullable<short> QtdEnfermeiroTercF { get; set; }
        public Nullable<short> QtdEnfermeiroTempM { get; set; }
        public Nullable<short> QtdEnfermeiroTempF { get; set; }
        public Nullable<short> QtdAuxTecEnfEfetivoM { get; set; }
        public Nullable<short> QtdAuxTecEnfEfetivoF { get; set; }
        public Nullable<short> QtdAuxTecEnfComisM { get; set; }
        public Nullable<short> QtdAuxTecEnfComisF { get; set; }
        public Nullable<short> QtdAuxTecEnfTercM { get; set; }
        public Nullable<short> QtdAuxTecEnfTercF { get; set; }
        public Nullable<short> QtdAuxTecEnfTempM { get; set; }
        public Nullable<short> QtdAuxTecEnfTempF { get; set; }
        public Nullable<short> QtdPsicologoEfetivoM { get; set; }
        public Nullable<short> QtdPsicologoEfetivoF { get; set; }
        public Nullable<short> QtdPsicologoComisM { get; set; }
        public Nullable<short> QtdPsicologoComisF { get; set; }
        public Nullable<short> QtdPsicologoTercM { get; set; }
        public Nullable<short> QtdPsicologoTercF { get; set; }
        public Nullable<short> QtdPsicologoTempM { get; set; }
        public Nullable<short> QtdPsicologoTempF { get; set; }
        public Nullable<short> QtdDentistaEfetivoM { get; set; }
        public Nullable<short> QtdDentistaEfetivoF { get; set; }
        public Nullable<short> QtdDentistaComisM { get; set; }
        public Nullable<short> QtdDentistaComisF { get; set; }
        public Nullable<short> QtdDentistaTercM { get; set; }
        public Nullable<short> QtdDentistaTercF { get; set; }
        public Nullable<short> QtdDentistaTempM { get; set; }
        public Nullable<short> QtdDentistaTempF { get; set; }
        public Nullable<short> QtdAuxTecOdontoEfetivoM { get; set; }
        public Nullable<short> QtdAuxTecOdontoEfetivoF { get; set; }
        public Nullable<short> QtdAuxTecOdontoComisM { get; set; }
        public Nullable<short> QtdAuxTecOdontoComisF { get; set; }
        public Nullable<short> QtdAuxTecOdontoTercM { get; set; }
        public Nullable<short> QtdAuxTecOdontoTercF { get; set; }
        public Nullable<short> QtdAuxTecOdontoTempM { get; set; }
        public Nullable<short> QtdAuxTecOdontoTempF { get; set; }
        public Nullable<short> QtdAssistSocialEfetivoM { get; set; }
        public Nullable<short> QtdAssistSocialEfetivoF { get; set; }
        public Nullable<short> QtdAssistSocialComisM { get; set; }
        public Nullable<short> QtdAssistSocialComisF { get; set; }
        public Nullable<short> QtdAssistSocialTercM { get; set; }
        public Nullable<short> QtdAssistSocialTercF { get; set; }
        public Nullable<short> QtdAssistSocialTempM { get; set; }
        public Nullable<short> QtdAssistSocialTempF { get; set; }
        public Nullable<short> QtdAdvogadoEfetivoM { get; set; }
        public Nullable<short> QtdAdvogadoEfetivoF { get; set; }
        public Nullable<short> QtdAdvogadoComisM { get; set; }
        public Nullable<short> QtdAdvogadoComisF { get; set; }
        public Nullable<short> QtdAdvogadoTercM { get; set; }
        public Nullable<short> QtdAdvogadoTercF { get; set; }
        public Nullable<short> QtdAdvogadoTempM { get; set; }
        public Nullable<short> QtdAdvogadoTempF { get; set; }
        public Nullable<short> QtdMedClinicoEfetivoM { get; set; }
        public Nullable<short> QtdMedClinicoEfetivoF { get; set; }
        public Nullable<short> QtdMedClinicoComisM { get; set; }
        public Nullable<short> QtdMedClinicoComisF { get; set; }
        public Nullable<short> QtdMedClinicoTercM { get; set; }
        public Nullable<short> QtdMedClinicoTercF { get; set; }
        public Nullable<short> QtdMedClinicoTempM { get; set; }
        public Nullable<short> QtdMedClinicoTempF { get; set; }
        public Nullable<short> QtdGinecologistaEfetivoM { get; set; }
        public Nullable<short> QtdGinecologistaEfetivoF { get; set; }
        public Nullable<short> QtdGinecologistaComisM { get; set; }
        public Nullable<short> QtdGinecologistaComisF { get; set; }
        public Nullable<short> QtdGinecologistaTercM { get; set; }
        public Nullable<short> QtdGinecologistaTercF { get; set; }
        public Nullable<short> QtdGinecologistaTempM { get; set; }
        public Nullable<short> QtdGinecologistaTempF { get; set; }
        public Nullable<short> QtdPsiquiatraEfetivoM { get; set; }
        public Nullable<short> QtdPsiquiatraEfetivoF { get; set; }
        public Nullable<short> QtdPsiquiatraComisM { get; set; }
        public Nullable<short> QtdPsiquiatraComisF { get; set; }
        public Nullable<short> QtdPsiquiatraTercM { get; set; }
        public Nullable<short> QtdPsiquiatraTercF { get; set; }
        public Nullable<short> QtdPsiquiatraTempM { get; set; }
        public Nullable<short> QtdPsiquiatraTempF { get; set; }
        public Nullable<short> QtdPedagogoEfetivoM { get; set; }
        public Nullable<short> QtdPedagogoEfetivoF { get; set; }
        public Nullable<short> QtdPedagogoComisM { get; set; }
        public Nullable<short> QtdPedagogoComisF { get; set; }
        public Nullable<short> QtdPedagogoTercM { get; set; }
        public Nullable<short> QtdPedagogoTercF { get; set; }
        public Nullable<short> QtdPedagogoTempM { get; set; }
        public Nullable<short> QtdPedagogoTempF { get; set; }
        public Nullable<short> QtdProfessorEfetivoM { get; set; }
        public Nullable<short> QtdProfessorEfetivoF { get; set; }
        public Nullable<short> QtdProfessorComisM { get; set; }
        public Nullable<short> QtdProfessorComisF { get; set; }
        public Nullable<short> QtdProfessorTercM { get; set; }
        public Nullable<short> QtdProfessorTercF { get; set; }
        public Nullable<short> QtdProfessorTempM { get; set; }
        public Nullable<short> QtdProfessorTempF { get; set; }
        public Nullable<short> QtdTerapeutaEfetivoM { get; set; }
        public Nullable<short> QtdTerapeutaEfetivoF { get; set; }
        public Nullable<short> QtdTerapeutaComisM { get; set; }
        public Nullable<short> QtdTerapeutaComisF { get; set; }
        public Nullable<short> QtdTerapeutaTercM { get; set; }
        public Nullable<short> QtdTerapeutaTercF { get; set; }
        public Nullable<short> QtdTerapeutaTempM { get; set; }
        public Nullable<short> QtdTerapeutaTempF { get; set; }
        public Nullable<short> QtdPolicialCEfetivoM { get; set; }
        public Nullable<short> QtdPolicialCEfetivoF { get; set; }
        public Nullable<short> QtdPolicialCComisM { get; set; }
        public Nullable<short> QtdPolicialCComisF { get; set; }
        public Nullable<short> QtdPolicialCTercM { get; set; }
        public Nullable<short> QtdPolicialCTercF { get; set; }
        public Nullable<short> QtdPolicialCTempM { get; set; }
        public Nullable<short> QtdPolicialCTempF { get; set; }
        public Nullable<short> QtdPolicialMEfetivoM { get; set; }
        public Nullable<short> QtdPolicialMEfetivoF { get; set; }
        public Nullable<short> QtdPolicialMComisM { get; set; }
        public Nullable<short> QtdPolicialMComisF { get; set; }
        public Nullable<short> QtdPolicialMTercM { get; set; }
        public Nullable<short> QtdPolicialMTercF { get; set; }
        public Nullable<short> QtdPolicialMTempM { get; set; }
        public Nullable<short> QtdPolicialMTempF { get; set; }
        public Nullable<System.DateTime> DataInsercao { get; set; }
    
        public virtual Crime Crime { get; set; }
        public virtual Educacao Educacao { get; set; }
        public virtual PopulacaoPrisional PopulacaoPrisional { get; set; }
        public virtual Saude Saude { get; set; }
        public virtual ServicosTerceirizados ServicosTerceirizados { get; set; }
        public virtual Tempo Tempo { get; set; }
        public virtual Trabalho Trabalho { get; set; }
        public virtual Unidade Unidade { get; set; }
    }
}
