//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saude()
        {
            this.FatoEstabelecimento = new HashSet<FatoEstabelecimento>();
            this.FatoSistemaPenitenciario = new HashSet<FatoSistemaPenitenciario>();
        }
    
        public int SkSaude { get; set; }
        public int NkUnidade { get; set; }
        public string St_ConsultorioMedico { get; set; }
        public string ConsultorioMedicoOutros { get; set; }
        public string St_ConsultorioOdonto { get; set; }
        public string ConsultorioOdontoOutros { get; set; }
        public string St_SalaColetaMatLab { get; set; }
        public string SalaColetaMatLabOutros { get; set; }
        public string St_PostoEnfermagem { get; set; }
        public string PostoEnfermagemOutros { get; set; }
        public string St_CelaObservacao { get; set; }
        public string CelaObservacaoOutros { get; set; }
        public string St_CelaEnfermariaSolario { get; set; }
        public string CelaEnfermariaSolarioOutros { get; set; }
        public string St_Farmacia { get; set; }
        public string FarmaciaOutros { get; set; }
        public string St_CentralMatEst { get; set; }
        public string CentralMatEstOutros { get; set; }
        public string St_SalaDescontaminacao { get; set; }
        public string SalaDescontaminacaoOutros { get; set; }
        public string St_SalaEsterilizacao { get; set; }
        public string SalaEsterilizacaoOutros { get; set; }
        public string St_Vestiario { get; set; }
        public string VestiarioOutros { get; set; }
        public string St_DepositoMatLimp { get; set; }
        public string DepositoMatLimpOutros { get; set; }
        public string St_SalaAtendClinicoMultiprof { get; set; }
        public string SalaAtendClinicoMultiprofOutros { get; set; }
        public string St_SalaProdecimentos { get; set; }
        public string SalaProdecimentosOutros { get; set; }
        public string St_SalaRaioX { get; set; }
        public string SalaRaioXOutros { get; set; }
        public string St_LaboratioDiagnostico { get; set; }
        public string LaboratioDiagnosticoOutros { get; set; }
        public string St_CelaEspera { get; set; }
        public string CelaEsperaOutros { get; set; }
        public string St_SolarioPacientes { get; set; }
        public string SolarioPacientesOutros { get; set; }
        public Nullable<System.DateTime> DataInsercao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoEstabelecimento> FatoEstabelecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoSistemaPenitenciario> FatoSistemaPenitenciario { get; set; }
    }
}
