//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicosTerceirizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicosTerceirizados()
        {
            this.FatoEstabelecimento = new HashSet<FatoEstabelecimento>();
            this.FatoSistemaPenitenciario = new HashSet<FatoSistemaPenitenciario>();
        }
    
        public int SkServicosTerceirizados { get; set; }
        public int NkUnidade { get; set; }
        public string ServicosTerc { get; set; }
        public string St_AlimentacaoTerc { get; set; }
        public string St_LimpezaTerc { get; set; }
        public string St_LavanderiaTerc { get; set; }
        public string St_SaudeTerc { get; set; }
        public string St_SegurancaTerc { get; set; }
        public string St_AssistenciaEducacionalTerc { get; set; }
        public string St_AssistenciaLaboralTerc { get; set; }
        public string St_AssistenciaSocialTerc { get; set; }
        public string St_AssistenciaJuridicaTerc { get; set; }
        public string St_AssistenciaAdmTerc { get; set; }
        public string OutrosServicosTerc { get; set; }
        public Nullable<System.DateTime> DataInsercao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoEstabelecimento> FatoEstabelecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoSistemaPenitenciario> FatoSistemaPenitenciario { get; set; }
    }
}
