//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tempo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tempo()
        {
            this.FatoEstabelecimento = new HashSet<FatoEstabelecimento>();
            this.FatoSistemaPenitenciario = new HashSet<FatoSistemaPenitenciario>();
        }
    
        public int SkTempo { get; set; }
        public System.DateTime Data { get; set; }
        public short Ano { get; set; }
        public short Mes { get; set; }
        public short Dia { get; set; }
        public short DiaSemana { get; set; }
        public short DiaAno { get; set; }
        public string AnoBissexto { get; set; }
        public string DiaUtil { get; set; }
        public string FimSemana { get; set; }
        public string Feriado { get; set; }
        public string PreFeriado { get; set; }
        public string PosFeriado { get; set; }
        public string NomeFeriado { get; set; }
        public string NomeDiaSemana { get; set; }
        public string NomeDiaSemanaAbrev { get; set; }
        public string NomeMes { get; set; }
        public string NomeMesAbrev { get; set; }
        public short Quinzena { get; set; }
        public short Bimestre { get; set; }
        public short Trimetre { get; set; }
        public short Semestre { get; set; }
        public short NrSemanaMes { get; set; }
        public short NrSemanaAno { get; set; }
        public string EstacaoAno { get; set; }
        public string DataPorExtento { get; set; }
        public string Evento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoEstabelecimento> FatoEstabelecimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatoSistemaPenitenciario> FatoSistemaPenitenciario { get; set; }
    }
}
