//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUnidade
    {
        public string NomeUnidade { get; set; }
        public string NomeRegistro { get; set; }
        public int NkUnidade { get; set; }
        public int SkUnidade { get; set; }
        public string Cidade { get; set; }
        public int SkCidade { get; set; }
        public string UF { get; set; }
        public string NomeUF { get; set; }
        public int SkUF { get; set; }
    }
}
